/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-12-24 07:30:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=BIG5");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=BIG5\">\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("<html lang=\"en\"><!-- Basic -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">   \r\n");
      out.write("   \r\n");
      out.write("    <!-- Mobile Metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write(" \r\n");
      out.write("     <!-- Site Metas -->\r\n");
      out.write("    <title>Health&Care</title>  \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Site Icons -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Pogo Slider CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/pogo-slider.min.css\">\r\n");
      out.write("\t<!-- Site CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">    \r\n");
      out.write("    <!-- Responsive CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkNameAndPassIsEmptyOrNot() \r\n");
      out.write("{ \r\n");
      out.write("\t\r\n");
      out.write("\tif (document.getElementById(\"login\").userIDText.value == \"\" && document.getElementById(\"login\").userPassText.value == \"\") \r\n");
      out.write("\t{ \r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"請輸入帳號/密碼\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.getElementById(\"login\").userIDText.value == \"\") \r\n");
      out.write("\t{ \r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"請輸入帳號\"); \r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.getElementById(\"login\").userPassText.value == \"\") \r\n");
      out.write("\t{ \r\n");
      out.write("\t\talert(\"請輸入密碼\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.getElementById(\"login\").userIDText.value != \"\" && document.getElementById(\"login\").userPassText.value != \"\") \r\n");
      out.write("\t{ \r\n");
      out.write("\t\tFORM1.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"something wrong!\");\r\n");
      out.write("\t}\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<body id=\"home\" data-spy=\"scroll\" data-target=\"#navbar-wd\" data-offset=\"98\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- LOADER -->\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("\t\t<div class=\"preloader pulse\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-heartbeat\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div><!-- end loader -->\r\n");
      out.write("    <!-- END LOADER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start header -->\r\n");
      out.write("\t<header class=\"top-header\">\r\n");
      out.write("\t\t<nav class=\"navbar header-nav navbar-expand-lg\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\"><img src=\"images/icon.png\" alt=\"image\"></a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar-wd\" aria-controls=\"navbar-wd\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbar-wd\">\r\n");
      out.write("                    <ul class=\"navbar-nav\">\r\n");
      out.write("                        <li><a class=\"nav-link\" href=\"#about\">About</a></li>\r\n");
      out.write("                        <li><a class=\"nav-link\" href=\"#family\">Health</a></li>\r\n");
      out.write("                        <li><a class=\"nav-link\" href=\"#events\">Care</a></li>\r\n");
      out.write("                        <li><a class=\"nav-link\" href=\"#loginpage\">Login</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- End header -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Banner -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- End Banner -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start About us -->\r\n");
      out.write("\t<div id=\"about\" class=\"about-box\">\r\n");
      out.write("\t\t<div class=\"about-a1\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Health <span>&</span> Care</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row align-items-center about-main-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2> About <span>Health</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>目的在於提供一個可以管理健康的平台，分析使用者的飲食習慣、運動習慣、睡眠習慣與個人的醫療資訊來達到健康上的管理和建議，並可以根據使用者的健康情況來建議一周需要運動幾次、一天需要睡眠多久等功能，讓使用者的健康能一直維持良好狀態。</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"about-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded\" src=\"images/health.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row align-items-center about-main-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"about-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded\" src=\"images/care.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2> About <span>Care</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>目的在於可以根據個人的健康管理和分析，可告知使用者哪些東西會引起過敏等症狀，並能夠依據醫療資訊分析使用者在食用上的食物是否會引起身體的不適等功能，來達到預防手段，合理的飲食可以讓使用者的身體更為健康，而不適當的飲食則會造成使用者的健康程度下降。</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End About us -->\r\n");
      out.write("\t<!-- Start Contact -->\r\n");
      out.write("\t<!-- <div id=\"contact\" class=\"contact-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Create account</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t  <div class=\"contact-block\">\r\n");
      out.write("\t\t\t\t\t<form id=\"contactForm\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Your Name\" required data-error=\"Please enter your name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>                                 \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Your Email\" id=\"email\" class=\"form-control\" name=\"name\" required data-error=\"Please enter your email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Password\" id=\"password\" class=\"form-control\" name=\"name\" required data-error=\"Please enter your password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Re-enter password\" id=\"Re-enter password\" class=\"form-control\" name=\"name\" required data-error=\"Please re-enter your password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"submit-button text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-common\" id=\"submit\" type=\"submit\">Create your account</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"msgSubmit\" class=\"h3 text-center hidden\"></div> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  </div>            \r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- End Contact -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Story -->\r\n");
      out.write("\t<!-- <div id=\"story\" class=\"story-box main-timeline-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Our Story</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row timeline-element separline\">\r\n");
      out.write("\t\t\t\t<div class=\"timeline-date-panel col-xs-12 col-md-6  align-left\">         \r\n");
      out.write("                    <div class=\"time-line-date-content\">\r\n");
      out.write("                        <p class=\"mbr-timeline-date mbr-fonts-style display-font\">\r\n");
      out.write("                            1 March 2018  \r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"iconBackground\"></span>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-6 align-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"timeline-text-content\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"mbr-timeline-title pb-3 mbr-fonts-style display-font\">First meet</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mbr-timeline-text mbr-fonts-style display-7\">\r\n");
      out.write("\t\t\t\t\t\t   We met at the wedding of our close friends and immediately found a common language, so a year later our first date happened.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row timeline-element reverse separline\">\r\n");
      out.write("\t\t\t\t<div class=\"timeline-date-panel col-xs-12 col-md-6  align-left\">         \r\n");
      out.write("                    <div class=\"time-line-date-content\">\r\n");
      out.write("                        <p class=\"mbr-timeline-date mbr-fonts-style display-font\">\r\n");
      out.write("                            2 April 2018  \r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"iconBackground\"></span>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-6 align-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"timeline-text-content\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"mbr-timeline-title pb-3 mbr-fonts-style display-font\">First date</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mbr-timeline-text mbr-fonts-style display-7\">\r\n");
      out.write("\t\t\t\t\t\t   We met at the wedding of our close friends and immediately found a common language, so a year later our first date happened.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row timeline-element separline\">\r\n");
      out.write("\t\t\t\t<div class=\"timeline-date-panel col-xs-12 col-md-6  align-left\">         \r\n");
      out.write("                    <div class=\"time-line-date-content\">\r\n");
      out.write("                        <p class=\"mbr-timeline-date mbr-fonts-style display-font\">\r\n");
      out.write("                            1 May 2018  \r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"iconBackground\"></span>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-6 align-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"timeline-text-content\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"mbr-timeline-title pb-3 mbr-fonts-style display-font\">Proposal</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mbr-timeline-text mbr-fonts-style display-7\">\r\n");
      out.write("\t\t\t\t\t\t   Fusce convallis ante id purus sagittis malesuada. Sed erat ipsum, suscipit sit amet auctor quis, vehicula ut leo. Maecenas felis nulla, tincidunt ac blandit a, consectetur quis elit.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row timeline-element reverse separline\">\r\n");
      out.write("\t\t\t\t<div class=\"timeline-date-panel col-xs-12 col-md-6  align-left\">         \r\n");
      out.write("                    <div class=\"time-line-date-content\">\r\n");
      out.write("                        <p class=\"mbr-timeline-date mbr-fonts-style display-font\">\r\n");
      out.write("                            2 June 2018  \r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"iconBackground\"></span>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-6 align-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"timeline-text-content\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"mbr-timeline-title pb-3 mbr-fonts-style display-font\">Engagement</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mbr-timeline-text mbr-fonts-style display-7\">\r\n");
      out.write("\t\t\t\t\t\t   Proin tempus felis quis justo pretium interdum. Praesent sollicitudin lectus eu mattis egestas. Praesent luctus magna at dignissim placerat.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- End Story -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Family -->\r\n");
      out.write("\t<div id=\"family\" class=\"family-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Health</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>健康人生六步驟</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single-team-member\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/weight.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Daily weight</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>記錄每天體重變化</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single-team-member\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/diet.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Daily diet</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>記錄每天飲食情況</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single-team-member\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/exercise.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Daily exercise</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>記錄每天運動情況</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single-team-member\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/sleep.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Daily Sleeping state</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>記錄每天睡眠情況</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single-team-member\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/body fat.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Daily Body fat</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>記錄每天體脂變化率</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single-team-member\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/metabolism.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"family-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Daily metabolism</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>記錄每天代謝率</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Family -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Gallery -->\r\n");
      out.write("\t<!-- <div id=\"gallery\" class=\"gallery-box\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Gallery</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<ul class=\"popup-gallery clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-01.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-01.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-02.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-02.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-03.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-03.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-04.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-04.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-05.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-05.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-06.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-06.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-07.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-07.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"images/gallery-08.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/gallery-08.jpg\" alt=\"single image\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"overlay\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- End Gallery -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Events -->\r\n");
      out.write("\t<div id=\"events\" class=\"events-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Care</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>愛護身體是為了可以長長久久</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"event-inner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"event-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/Food allergy.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h2>Food allergy</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>提供食物過敏查詢</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"event-inner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"event-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/Alcohol addiction.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h2>Alcohol addiction</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>提供查詢攝取過多酒量對身體的危害程度</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"event-inner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"event-img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"images/Cigarette addiction.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h2>Cigarette addiction</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>提供查詢吸取過量的菸會對身體危害程度</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Events -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Contact -->\r\n");
      out.write("\t<div id=\"loginpage\" class=\"show\"\r\n");
      out.write("\t\t\tstyle=\"margin: 0px auto; height: 300px; width: 1200px\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Create account</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"loginpage\" >\r\n");
      out.write("\t\t\t<form action=\"UserInfoServlet\" method=post name=FORM1 id=login>\r\n");
      out.write("\t\t\t\t<span style=\"margin: 0px auto;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=text class=\"form-control\" name=userIDText value=\"\" placeholder=\"Account\" required data-error=\"Please enter your name\">\r\n");
      out.write("\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t<BR />\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=password class=\"form-control\" name=userPassText value=\"\" placeholder=\"Password\" required data-error=\"Please enter your password\">\r\n");
      out.write("\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<BR />\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"submit-button text-center\"> \r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"送出\" name=button1 onClick=\"checkNameAndPassIsEmptyOrNot()\" /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"清除\" name=reset1 />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- End Contact -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t<footer class=\"footer-box\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ALL JS FILES -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- ALL PLUGINS -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.pogo-slider.min.js\"></script> \r\n");
      out.write("\t<script src=\"js/slider-index.js\"></script>\r\n");
      out.write("\t<script src=\"js/smoothscroll.js\"></script>\r\n");
      out.write("\t<script src=\"js/form-validator.min.js\"></script>\r\n");
      out.write("    <script src=\"js/contact-form-script.js\"></script>\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
